language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt # install package + test dependencies
before_script: cd src
script: pytest pytester.py # run tests
after_success:
  - codecov --file coverage/lcov.info --disable search # submit coverage